- name: Install apptainer
  vars:
    apptainer_dir: "{{ common_dir }}/apptainer"
    apptainer_module_dir: "{{ common_modules }}/apptainer"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ apptainer_dir }}/{{ version_number }}"
    go_location: "{{ item.go_location }}"
    squashfuse_location: "{{ item.squashfuse_location }}"
    gocryptfs_location: "{{ item.gocryptfs_location }}"
    squashfuse_module: "{{ item.squashfuse_module }}"
    gocryptfs_module: "{{ item.gocryptfs_module }}"
  environment:
    LD_LIBRARY_PATH: "{{ squashfuse_location }}/lib:{{ gocryptfs_location }}/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"
    PKG_CONFIG_PATH: "{{ squashfuse_location }}/lib/pkgconfig:{{ gocryptfs_location }}/lib/pkgconfig:{{ ansible_env.PKG_CONFIG_PATH | default('') }}"
    INCLUDE: "{{ squashfuse_location }}/include:{{ gocryptfs_location }}/include:{{ ansible_env.INCLUDE | default('') }}"
    LIBRARY_PATH: "{{ squashfuse_location }}/lib:{{ gocryptfs_location }}/lib:{{ ansible_env.LIBRARY_PATH | default('') }}"
    PATH: "{{ squashfuse_location }}/bin:{{ gocryptfs_location }}/bin:{{ ansible_env.PATH }}"
  tags:
    - never
    - apptainer{{ item.version_number }}
  block:
    - name: Install apptainer {{ version_number }}
      vars:
        unzip_dir: "/dev/shm/apptainer-{{ version_number }}"
      block:
        - name: Download and install apptainer {{ version_number }}
          block:
            - name: Download apptainer {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/apptainer-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip apptainer {{ version_number }}
              unarchive:
                src: "{{ common_src }}/apptainer-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzip_dir }}"
            - name: Ensure installation parent exists
              file:
                path: "{{ apptainer_dir }}"
                state: directory
                mode: u=rwx,g=rx,o=rx
            - name: Configure apptainer
              command: "./mconfig --prefix={{ install_dir }} --localstatedir=/usr/local/var --sysconfdir={{ install_dir }}/etc --with-suid"
              args:
                chdir: "{{ unzip_dir }}"
                creates: "{{ unzip_dir }}/builddir/Makefile"
              environment:
                PATH: "{{ go_location }}:{{ ansible_env.PATH }}"
            - name: Compile apptainer
              make:
                chdir: "{{ unzip_dir }}/builddir"
              environment:
                PATH: "{{ go_location }}:{{ ansible_env.PATH }}"
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install apptainer
              make:
                chdir: "{{ unzip_dir }}/builddir"
                target: install
              become: true

    - name: Install apptainer {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ apptainer_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install apptainer {{ version_number }} module file
          template:
            src: common/apptainer.lua
            dest: "{{ apptainer_module_dir }}/{{ version_number }}.lua"

    - name: Configure apptainer {{ version_number }}
      block:
        - name: Ensure apptainer config directory exists
          file:
            path: "{{ install_dir }}/etc/apptainer"
            state: directory
            mode: u=rwx,g=rx,o=rx
            owner: root
            group: root
          become: true
        - name: Deploy apptainer configuration file
          template:
            src: common/apptainer.conf
            dest: "{{ install_dir }}/etc/apptainer/apptainer.conf"
            mode: u=rw,g=r,o=r
            owner: root
            group: root
            backup: yes
          become: true
