- name: Install gocryptfs
  vars:
    gocryptfs_dir: "{{ common_dir }}/gocryptfs"
    gocryptfs_module_dir: "{{ common_modules }}/gocryptfs"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ gocryptfs_dir }}/{{ version_number }}"
  tags:
    - never
    - gocryptfs{{ item.version_number }}
  block:
    - name: Install gocryptfs {{ version_number }}
      vars:
        unzip_dir: "/dev/shm/gocryptfs-{{ version_number }}"
      block:
        - name: Download and install gocryptfs {{ version_number }}
          block:
            - name: Download gocryptfs {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/gocryptfs-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"

            - name: Ensure installation directory {{ install_dir }} exists
              file:
                path: "{{ install_dir }}"
                state: directory
                mode: u=rwx,g=rx,o=rx
                recurse: true
            - name: Unzip gocryptfs {{ version_number }}
              unarchive:
                src: "{{ common_src }}/gocryptfs-{{ version_number }}.tar.gz"
                dest: "{{ install_dir }}"
                creates: "{{ unzip_dir }}"

    - name: Install gocryptfs {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ gocryptfs_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install gocryptfs {{ version_number }} module file
          template:
            src: common/gocryptfs.lua
            dest: "{{ gocryptfs_module_dir }}/{{ version_number }}.lua"
