- name: Install singularity
  vars:
    singularity_dir: "{{ common_dir }}/singularity"
    singularity_module_dir: "{{ common_modules }}/singularity"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ singularity_dir }}/{{ version_number }}"
    go_location: "{{ item.go_location }}"
  tags:
    - never
    - singularity{{ item.version_number }}
  environment:
    PATH: "{{ go_location }}:{{ ansible_env.PATH }}"
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
  block:
    - name: Install singularity {{ version_number }}
      when: "version_number.startswith('3') or version_number.startswith('4')"
      vars:
        unzip_dir: "/dev/shm/singularity-ce-{{ version_number }}"
      block:
        - name: Download and install singularity {{ version_number }}
          block:
            - name: Download singularity {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/singularity-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip singularity {{ version_number }}
              unarchive:
                src: "{{ common_src }}/singularity-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzip_dir }}"
            - name: Ensure installation parent exists
              file:
                path: "{{ singularity_dir }}"
                state: directory
                mode: o=rwx,g=rx,o=rx
            - name: Configure singularity
              command: "./mconfig --prefix={{ install_dir }} --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc{% if version_number is version('3.10', '>=') %} --without-seccomp{% endif %}{% if version_number is version('3.10', '>=') and version_number is version('4.3.0', '<') %} --without-conmon{% endif %}"
              args:
                chdir: "{{ unzip_dir }}"
                creates: "{{ unzip_dir }}/builddir/Makefile"
            - name: Compile singularity
              make:
                chdir: "{{ unzip_dir }}/builddir"
            - name: Install singularity
              make:
                chdir: "{{ unzip_dir }}/builddir"
                target: install
              become: true
    - name: Install singularity {{ version_number }}
      when: "version_number.startswith('2')"
      vars:
        unzip_dir: "/dev/shm/singularity-{{ version_number }}"
      block:
        - name: Download and install singularity {{ version_number }}
          block:
            - name: Download singularity {{ version_number }}
              get_url:
                url: "https://github.com/singularityware/singularity/releases/download/{{ version_number }}/singularity-{{ version_number }}.tar.gz"
                dest: "{{ common_src }}/singularity-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip singularity {{ version_number }}
              unarchive:
                src: "{{ common_src }}/singularity-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzip_dir }}"
            - name: Ensure installation parent exists
              file:
                path: "{{ singularity_dir }}"
                state: directory
                mode: o=rwx,g=rx,o=rx
            - name: Configure singularity (non-go)
              command: "./configure --prefix={{ install_dir }} --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc"
              args:
                chdir: "{{ unzip_dir }}"
            - name: Compile singularity (non-go)
              make:
                chdir: "{{ unzip_dir }}"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install singularity
              make:
                chdir: "{{ unzip_dir }}"
                target: install
              become: true

    - name: Install singularity {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ singularity_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install singularity {{ version_number }} module file
          template:
            src: singularity.lua
            dest: "{{ singularity_module_dir }}/{{ version_number }}.lua"
