- name: Create Population Genetics {{ item.version_number }} container
  vars:
    - base_container_image: "{{ common_container_dir }}/{{ item.base_container_name }}.sif"
    - version_number: "{{ item.version_number }}"
    - container_name: "PopGen_{{ item.version_number }}"
    - container_recipe: "{{ bio_container_recipe_dir }}/{{ container_name }}.def"
    - container_image: "{{ bio_container_dir }}/{{ container_name }}.sif"
    - arlecore: "{{ item.arlecore }}"
    - beast: "{{ item.beast }}"
    - plink2: "{{ item.plink2 }}"
    - bcftools: "{{ item.bcftools }}"
    - admixture: "{{ item.admixture }}"
    - shapeit: "{{ item.shapeit }}"
    - eigensoft: "{{ item.eigensoft }}"
    - finestructure: "{{ item.finestructure }}"
    - beagle: "{{ item.beagle }}"
    - popgen_module_dir: "{{ bio_modules }}/popgen"
  tags:
    - "popgen{{ item.version_number }}"
    - never
  block:
    - name: "Check for existence of {{ base_container_image }} container"
      stat:
        path: "{{ base_container_image }}"
      register: base_container_exists
    - name: "Missing {{ base_container_image }}"
      fail:
        msg: "The container {{ base_container_image }} is missing."
      when: base_container_exists.stat.exists == False
    - name: Create PopGen {{ version_number }} container
      when: base_container_exists.stat.exists == True
      block:
        - name: Copy recipe  {{ container_recipe }}
          template:
            src: "PopGen.def"
            dest: "{{ container_recipe }}"
        - name: Download arlecore {{ arlecore.version }}
          get_url:
            url: "{{ arlecore.url }}"
            dest: "{{ bio_src }}/arlsecore_linux.{{ arlecore.version }}.zip"
            checksum: "sha256:{{ arlecore.checksum }}"
        - name: Download beast {{ beast.version }}
          get_url:
            url: "{{ beast.url }}"
            dest: "{{ bio_src }}/BEASTv{{ beast.version }}.tgz"
            checksum: "sha256:{{ beast.checksum }}"
        - name: Download plink2 {{ plink2.version }}
          get_url:
            url: "{{ plink2.url }}"
            dest: "{{ bio_src }}/plink2_linux_x86_64.{{ plink2.version }}.zip"
            checksum: "sha256:{{ plink2.checksum }}"
        - name: Download bcftools {{ bcftools.version }}
          get_url:
            url: "{{ bcftools.url }}"
            dest: "{{ bio_src }}/bcftools-{{ bcftools.version }}.tar.bz2"
            checksum: "sha256:{{ bcftools.checksum }}"
        - name: Download admixture {{ admixture.version }}
          get_url:
            url: "{{ admixture.url }}"
            dest: "{{ bio_src }}/admixture-{{ admixture.version }}.tar.gz"
            checksum: "sha256:{{ admixture.checksum }}"
        - name: Download shapeit {{ shapeit.version }} 
          get_url:
            url: "{{ shapeit.url }}"
            dest: "{{ bio_src }}/shapeit-{{ shapeit.version }}.tar.gz"
            checksum: "sha256:{{ shapeit.checksum }}"
        - name: Download eigensoft {{ eigensoft.version }}
          get_url:
            url: "{{ eigensoft.url }}"
            dest: "{{ bio_src }}/eigensoft-v{{ eigensoft.version }}.tar.gz"
            checksum: "sha256:{{ eigensoft.checksum }}"
        - name: Download finestructure {{ finestructure.version }}
          get_url:
            url: "{{ finestructure.url }}"
            dest: "{{ bio_src }}/finestructure-{{ finestructure.version }}.tar.gz"
            checksum: "sha256:{{ finestructure.checksum }}"
        - name: Download Beagle {{ beagle.version }}
          get_url:
            url: "{{ beagle.url }}"
            dest: "{{ bio_src }}/beagle-v{{ beagle.version }}.tar.gz"
            checksum: "sha256:{{ beagle.checksum }}"

        - name: Build container {{ container_image }}
          command: "{{ singularity }} build {{ container_image }} {{ container_recipe }}"
          args:
            creates: "{{ container_image }}"
          become: yes
#          environment:
#            SINGULARITY_TMPDIR: "/dev/shm"

    - name: Install PopGen {{ container_name }} module
      block:
        - name: Check module dir
          file:
            path: "{{ popgen_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install PopGen {{ version_number }} module file
          template:
            src: PopGen.lua
            dest: "{{ popgen_module_dir }}/{{ version_number }}.lua"


#  Plink2+bcftools1.10.2+R3.5+ADMIXTURE
#  or
#  R3.5.1+Arlequin+BEASTv1.8
