---
- name: Install bcftools {{ item.version_number }}
  vars:
    bcftools_dir: "{{ bio_dir }}/bcftools"
    bcftools_module_dir: "{{ bio_modules }}/bcftools"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ bcftools_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/bcftools-{{ version_number }}"
  tags:
    - never
    - bcftools{{ item.version_number }}

  block:
    - name: Download and install bcftools {{ version_number }}
      block:
      - name: Download bcftools {{ version_number }} from {{ url }}
        get_url:
          url: "{{ url }}"
          dest: "{{  bio_dir }}/src/bcftools.tar.bz2"
          checksum: "{{ checksum }}"
      - name: Ensure bcftools dir exists
        file:
          path: "{{ bcftools_dir }}"
          state: directory
      - name: Uncompress bcftools to {{ unzip_dir }}
        unarchive:
          src: "{{  bio_dir }}/src/bcftools.tar.bz2"
          dest: "/dev/shm"
          creates: "{{ unzip_dir }}"
      - name: Run bcftools {{ version_number }} configure
        command: "./configure --prefix={{ install_dir }}"
        args:
          chdir: "{{ unzip_dir }}"
      - name: Make bcftools {{ version_number }}
        make:
          chdir: "{{ unzip_dir }}"
        environment:
          MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
      - name: Install bcftools {{ version_number }} to {{ install_dir }}
        make:
          chdir: "{{ unzip_dir }}"
          target: "install"

    - name: Install bcftools {{ version_number }} module
      block:
        - name: Check module dir {{ bcftools_module_dir }}
          file:
            path: "{{ bcftools_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install bcftools {{ version_number }} module file
          template:
            src: bcftools.lua
            dest: "{{ bcftools_module_dir }}/{{ version_number }}.lua"
