---
- name: Install bwa {{ item.version_number }}
  vars:
    bwa_dir: "{{ bio_dir }}/bwa"
    bwa_module_dir: "{{ bio_modules }}/bwa"
    repo: "{{ item.repo }}"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ bwa_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/bwa-{{ version_number }}"
  tags:
    - never
    - bwa{{ item.version_number }}

  block:
    - name: Download and install bwa ({{ version_number }})
      block:
        - name: Clone bwa {{ version_number }} from {{ repo }}
          git:
            repo: "{{ repo }}"
            dest: "{{ unzip_dir }}"
        - name: Ensure bwa dir exists
          file:
            path: "{{ install_dir }}"
            state: directory
            recurse: yes
        - name: Make bwa {{ version_number }}
          make:
            chdir: "{{ unzip_dir }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
        - name: "Copy bwa and bwakit to {{ install_dir }}"
          command: "mv {{ unzip_dir }}/bwa {{ unzip_dir }}/bwakit {{ install_dir }}"
          args:
            creates: "{{ install_dir }}/bwa"

#    - name: Install bwa {{ version_number }} module
#      block:
#        - name: Check module dir {{ bwa_module_dir }}
#          file:
#            path: "{{ bwa_module_dir }}"
#            state: directory
#            mode: u=rwx,g=rwx,o=rx
#        - name: Install bwa {{ version_number }} module file
#          template:
#            src: bwa.lua
#            dest: "{{ bwa_module_dir }}/{{ version_number }}.lua"
