---
- debug:
    msg: "Note tag: canvas{{ item.version_number }}"

- name: Install Canvas {{ item.version_number }}
  vars:
    canvas_dir: "{{ bio_dir }}/canvas"
    canvas_module_dir: "{{ bio_modules }}/canvas"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ canvas_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/Canvas-{{ version_number }}+master_x64"
    url: "{{ item.url }}"
  tags:
    - never
    - canvas{{ item.version_number }}

  block:
    - name: Check if canvas already installed
      stat: path="{{ install_dir }}"
      register: canvas_stat
    - name: Download and install Canvas {{ version_number }}
      when: not canvas_stat.stat.exists
      block:
      - name: Download Canvas {{ version_number }} from {{ url }}
        get_url:
          url: "{{ url }}"
          dest: "{{ bio_src }}/Canvas-{{ version_number }}.tar.gz"
          checksum: "{{ checksum }}"
      - name: Unzip Canvas {{ version_number }}
        unarchive:
          src: "{{ bio_src }}/Canvas-{{ version_number }}.tar.gz"
          dest: "/dev/shm"
          creates: "{{ unzip_dir }}"
      - name: Check {{ canvas_dir }} directory
        file:
          path: "{{ canvas_dir }}"
          state: directory
          mode: u=wrx,g=rwx,o=rx
      - name: Move {{ unzip_dir }} to {{ install_dir }}
        command: "mv {{ unzip_dir }} {{ install_dir }}"

    - name: Install Canvas {{ version_number }} module
      block:
      - name: Check {{ canvas_module_dir }} dir
        file:
          path: "{{ canvas_module_dir }}"
          state: directory
          mode: u=rwx,g=rwx,o=rx
      - name: Install Canvas module file
        template:
          src: canvas.lua
          dest: "{{ canvas_module_dir }}/{{ version_number }}.lua"
