---
- name: Install disk_management
  vars:
    disk_management_dir: "{{ common_dir }}/disk_management"
    git_repo: "git@github.com:idia-astro/admin-tools.git"
  tags:
    - never
    - disk_management

  block:
    - name: Clone git repo, setup venv and install
      block:
        - name: create private dir to clone to
          file:
              path: /dev/shm/admin_tools
              state: directory
              mode: "u=rwx,g=,o="
        - name: clone repo
          git:
            repo: "{{ git_repo }}"
            dest: /dev/shm/admin_tools
            update: yes
        - name: Create virtual_environment
          pip:
            name:
             - "."
             - ipython
            virtualenv: "{{ disk_management_dir }}"
            virtualenv_command: "{{ python_dir }}/bin/virtualenv"
            virtualenv_python: "{{ python_dir }}/bin/python"
            chdir: "/dev/shm/admin_tools/disk_management"
        - name: Clean cloned repo
          file:
              path: /dev/shm/admin_tools
              state: absent

    - name: Install disk_management module file
      template:
        src: disk_management.lua
        dest: "{{ common_modules }}/disk_management.lua"
