- name: Install LAPACK
  vars:
    lapack_dir: "{{ common_dir }}/LAPACK"
    lapack_module_dir: "{{ common_modules }}/LAPACK"
    url: "https://github.com/Reference-LAPACK/lapack/archive/v{{ item.version_number }}.tar.gz"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ lapack_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/lapack-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - lapack{{ item.version_number }}
  block:
    - name: Install LAPACK {{ version_number }}
      block:
        - name: Download, compile and install LAPACK {{ version_number }}
          block:
          - name: Download LAPACK {{ version_number }}
            get_url:
              url: "{{ url }}"
              dest: "{{ common_src }}/lapack-v{{ version_number }}.tar.gz"
              checksum: "{{ checksum }}"
          - name: Unzip LAPACK {{ version_number }}
            unarchive:
              src: "{{ common_src }}/lapack-v{{ version_number }}.tar.gz"
              dest: "/dev/shm/"
              creates: "{{ unzipdir }}"
          - name: Ensure LAPACK build directory {{ build_dir }} is present
            file:
              path: "{{ build_dir }}"
              state: directory
          - name: Run cmake for LAPACK {{ version_number }}
            command: "cmake -DCMAKE_INSTALL_PREFIX:PATH={{ install_dir }} .."
            args:
              chdir: "{{ build_dir }}"
              creates: "{{ build_dir }}/Makefile"
          - name: Build LAPACK {{ version_number }}
            make:
              chdir: "{{ build_dir }}"
              target: "all"
            environment:
              MAKEFLAGS: "-j {{ ansible_processor_count }}"
          - name: Install LAPACK {{ version_number }} to {{ install_dir }}
            make:
              chdir: "{{ build_dir }}"
              target: "install"

    - name: Install LAPACK {{ version_number }} module
      block:
      - name: Check LAPACK module dir
        file:
          path: "{{ lapack_module_dir }}"
          state: directory
          mode: u=rwx,g=rwx,o=rx
      - name: Install LAPACK {{ version_number }} module file
        template:
          src: lapack.lua
          dest: "{{ lapack_module_dir }}/{{ version_number }}.lua"
