- name: Install LaTeX
  vars:
    latex_dir: "{{ common_dir }}/latex"
    latex_module_dir: "{{ common_modules }}/latex"
    texlive_install_file: "{{ item.texlive_install_file }}"
    texlive_profile: "{{ item.texlive_profile }}"
    version_number: "{{ item.version_number }}"
  tags:
    - never
    - latex-{{ item.version_number }}
  block:
    - name: Install LaTeX {{ version_number }}
      block:
        - name: copy texlive files
          copy:
            src: "{{ texlive_file.source }}"
            dest: "{{ texlive_file.dest }}"
          loop:
            - { source: "{{ texlive_install_file }}", dest: "/dev/shm/install-tl-unx.tar.gz" }
            - { source: "{{ texlive_profile }}", dest: "/dev/shm/texlive.profile" }
          loop_control:
            loop_var: "texlive_file"
        - name: Uncompress texlive install
          unarchive:
            src: "/dev/shm/install-tl-unx.tar.gz"
            dest: "/dev/shm"
            creates: "/dev/shm/install-tl-{{ item.version_number }}"
        - name: Install texlive using profile
          command: "./install-tl --profile=texlive.profile"
          args:
              chdir: "/dev/shm/install-tl-{{ item.version_number }}"
              creates: "/dev/shm/install-tl-{{ item.version_number }}/texlive"

#    - name: Check module dir
#      file:
#        path: "{{ latex_module_dir }}"
#        state: directory
#        mode: u=rwx,g=rwx,o=rx
#    - name: Install latex module file
#      template:
#        src: latex.lua
#        dest: "{{ latex_module_dir }}/{{ version_number }}.lua"
