---
- name: Install PLINK {{ item.version_number }}
  vars:
    plink_dir: "{{ bio_dir }}/plink"
    plink_module_dir: "{{ bio_modules }}/plink"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ plink_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/plink-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
    plink_url: "https://github.com/chrchang/plink-ng/releases/download/v{{ version_number }}/plink2_linux_x86_64.zip"
  tags:
    - never
    - plink{{ item.version_number }}

  block:
    - name: Download, compile and install PLINK {{ version_number }}
      block:
      - name: Download PLINK {{ version_number }} from {{ plink_url }}
        get_url:
          url: "{{ plink_url }}"
          dest: "{{ bio_src }}/plink2_linux_x86_64.{{ version_number }}.zip"
          checksum: "sha256:{{ checksum }}"
      - name: Ensure PLINK directory {{ install_dir }} exists
        file:
          path: "{{ install_dir }}"
          state: directory
      - name: Unzip PLINK {{ version_number }}
        unarchive:
          src: "{{ bio_src }}/plink2_linux_x86_64.{{ version_number }}.zip"
          dest: "{{ install_dir }}/"
          creates: "{{ install_dir }}/plink2"
    - name: Install plink {{ version_number }} module
      block:
      - name: Check module dir
        file:
          path: "{{ plink_module_dir }}"
          state: directory
          mode: u=rwx,g=rwx,o=rx
      - name: Install plink module file
        template:
          src: plink.lua
          dest: "{{ plink_module_dir }}/{{ version_number }}.lua"