---
- name: Install VarFish {{ item.version_number }}
  vars:
    varfish_dir: "{{ bio_dir }}/varfish"
    varfish_module_dir: "{{ bio_modules }}/varfish"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ varfish_dir }}/{{ item.version_number }}"
    java_module: "{{ item.java_module }}"
    java_location: "{{ item.java_location }}"
  tags:
    - never
    - varfish
  block:
    - name: Download, compile and install VarFish {{ version_number }}
      block:
        - name: Ensure varfish directory exists
          file:
            path: "{{ install_dir }}"
            state: directory
            mode: u=rwx,g=rx,o=rx
        - name: Download VarFish {{ version_number }}
          get_url:
              url: "{{ item.url }}"
              dest: "{{ install_dir }}/varfish-annotator.jar"
              checksum: "{{ checksum }}"
              mode: u=rw,g=r,o=r

#    - name: Install VarFish {{ version_number }} module
#      block:
#        - name: Check module dir
#          file:
#            path: "{{ varfish_module_dir }}"
#            state: directory
#            mode: u=rwx,g=rwx,o=rx
#        - name: Install VarFish module file
#          template:
#            src: varfish.lua
#            dest: "{{ varfish_module_dir }}/git.lua"
