---
- name: Install abricate {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    abricate_dir: "{{ bio_dir }}/abricate"
    abricate_module_dir: "{{ bio_modules }}/abricate"
    version_number: "{{ item.version_number }}"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    unzip_dir: "/dev/shm/abricate-{{ version_number }}"
    install_dir: "{{ abricate_dir }}/{{ version_number }}"
  tags:
    - never
    - abricate{{ item.version_number }}
  block:
    - name: Download and install abricate ({{ version_number }})
      block:
        - name: Clone abricate repository
          git:
            repo: "{{ git_repo }}"
            dest: "{{ unzip_dir }}"
            version: "{{ git_tag }}"
            force: yes

        - name: Ensure abricate dir exists
          file:
            path: "{{ abricate_dir }}"
            state: directory
            recurse: yes

        - name: Copy abricate to install directory
          command: "cp -r {{ unzip_dir }} {{ install_dir }}"
          args:
            creates: "{{ install_dir }}/bin"

        - name: Make abricate executable
          file:
            path: "{{ install_dir }}/bin/abricate"
            mode: '0755'

        - name: Setup abricate databases
          shell: "{{ install_dir }}/bin/abricate --setupdb"
          args:
            creates: "{{ install_dir }}/db"
          environment:
            PATH: "{{ install_dir }}/bin:{{ ansible_env.PATH }}"

    - name: Install abricate {{ version_number }} module
      block:
        - name: Check module dir {{ abricate_module_dir }}
          file:
            path: "{{ abricate_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install abricate {{ version_number }} module file
          template:
            src: bio/abricate.lua
            dest: "{{ abricate_module_dir }}/{{ version_number }}.lua"