---
- name: Install amrfinder {{ item.version_number }}
  vars:
    amrfinder_dir: "{{ bio_dir }}/amrfinder"
    amrfinder_module_dir: "{{ bio_modules }}/amrfinder"
    version_number: "{{ item.version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    unzip_dir: "/dev/shm/amrfinder-{{ version_number }}"
    install_dir: "{{ amrfinder_dir }}/{{ version_number }}"
    blast_module: "{{ item.blast_module | default('blast/2.16.0') }}"
    hmmer_module: "{{ item.hmmer_module | default('hmmer/3.4') }}"
  tags:
    - never
    - amrfinder{{ item.version_number }}
  block:
    - name: Download and install amrfinder ({{ version_number }})
      block:
        - name: Download amrfinder {{ version_number }} from {{ url }}
          get_url:
            url: "{{ url }}"
            dest: "{{ bio_src }}/amrfinder-{{ version_number }}.tar.gz"
            checksum: "{{ checksum }}"
            timeout: 300

        - name: Ensure amrfinder dir exists
          file:
            path: "{{ install_dir }}"
            state: directory
            mode: "ug=rwx,o=rx"
            recurse: yes

        - name: Unpack amrfinder {{ version_number }} directly to install directory
          unarchive:
            src: "{{ bio_src }}/amrfinder-{{ version_number }}.tar.gz"
            dest: "{{ install_dir }}"
            creates: "{{ install_dir }}/amrfinder"
            remote_src: yes

        - name: Make amrfinder binaries executable
          file:
            path: "{{ install_dir }}/{{ amr_binary }}"
            mode: '0755'
          loop:
            - amrfinder
            - amrfinder_update
            - fasta_check
            - gff_check
          loop_control:
            loop_var: amr_binary

        - name: Update AMRFinder database
          shell: "{{ install_dir }}/amrfinder --update"
          args:
            creates: "{{ install_dir }}/data"
          environment:
            PATH: "/software/bio/{{ blast_module }}/bin:{{ install_dir }}:{{ ansible_env.PATH }}"
          ignore_errors: yes

    - name: Install amrfinder {{ version_number }} module
      block:
        - name: Check module dir {{ amrfinder_module_dir }}
          file:
            path: "{{ amrfinder_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install amrfinder {{ version_number }} module file
          template:
            src: bio/amrfinder.lua
            dest: "{{ amrfinder_module_dir }}/{{ version_number }}.lua"