---
- name: Install ariba {{ item.version_number }}
  vars:
    ariba_dir: "{{ bio_dir }}/ariba"
    ariba_module_dir: "{{ bio_modules }}/ariba"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ ariba_dir }}/{{ version_number }}"
  tags:
    - never
    - ariba{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create ariba directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.ariba.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: Install ariba {{ version_number }} module
      block:
        - name: Check module dir {{ ariba_module_dir }}
          file:
            path: "{{ ariba_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install ariba {{ version_number }} module file
          template:
            src: bio/ariba.lua
            dest: "{{ ariba_module_dir }}/{{ version_number }}.lua"