---
- name: Install checkv {{ item.version_number }}
  vars:
    checkv_dir: "{{ bio_dir }}/checkv"
    checkv_module_dir: "{{ bio_modules }}/checkv"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ checkv_dir }}/{{ version_number }}"
  tags:
    - never
    - checkv{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create checkv directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.checkv.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create checkv module directory {{ checkv_module_dir }}"
      file:
          path: "{{ checkv_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install checkv module file"
      template:
        src: bio/checkv.lua
        dest: "{{ checkv_module_dir }}/{{ version_number }}.lua"