---
- name: Install checkm {{ item.version_number }}
  vars:
    checkm_dir: "{{ bio_dir }}/checkm"
    checkm_module_dir: "{{ bio_modules }}/checkm"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.11') }}"
    install_dir: "{{ checkm_dir }}/{{ version_number }}"
  tags:
    - never
    - checkm{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create checkm directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv configuration files for checkm
      copy:
        src: "uv/bio/checkm/{{ version_number }}/{{ uv_file }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ug=rw,o=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: uv_file

    - name: Create uv virtual environment for checkm
      command: "{{ python_location }}/bin/uv venv .venv --python {{ python_location }}/bin/python3"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv/bin/python"

    - name: Install checkm and dependencies with uv
      command: "{{ python_location }}/bin/uv sync"
      args:
        chdir: "{{ install_dir }}"

    - name: "Create checkm module directory {{ checkm_module_dir }}"
      file:
          path: "{{ checkm_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install checkm module file"
      template:
        src: bio/checkm.lua
        dest: "{{ checkm_module_dir }}/{{ version_number }}.lua"