---
- name: Install fastp {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    fastp_dir: "{{ bio_dir }}/fastp"
    fastp_module_dir: "{{ bio_modules }}/fastp"
    version_number: "{{ item.version_number }}"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    unzip_dir: "/dev/shm/fastp-{{ version_number }}"
    install_dir: "{{ fastp_dir }}/{{ version_number }}"
  tags:
    - never
    - fastp{{ item.version_number }}
  block:
    - name: Download and install fastp ({{ version_number }})
      block:
        - name: Clone fastp repository
          git:
            repo: "{{ git_repo }}"
            dest: "{{ unzip_dir }}"
            version: "{{ git_tag }}"
            force: yes

        - name: Ensure fastp dir exists
          file:
            path: "{{ fastp_dir }}"
            state: directory
            recurse: yes

        - name: Create install directory
          file:
            path: "{{ install_dir }}/bin"
            state: directory
            recurse: yes

        - name: Compile fastp
          make:
            chdir: "{{ unzip_dir }}"
            jobs: "{{ ansible_processor_count }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_count }}"

        - name: Copy fastp binary to install directory
          copy:
            src: "{{ unzip_dir }}/fastp"
            dest: "{{ install_dir }}/bin/fastp"
            mode: '0755'
            remote_src: yes

    - name: Install fastp {{ version_number }} module
      block:
        - name: Check module dir {{ fastp_module_dir }}
          file:
            path: "{{ fastp_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install fastp {{ version_number }} module file
          template:
            src: bio/fastp.lua
            dest: "{{ fastp_module_dir }}/{{ version_number }}.lua"