---
- name: Install fastmlst {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    fastmlst_dir: "{{ bio_dir }}/fastmlst"
    fastmlst_module_dir: "{{ bio_modules }}/fastmlst"
    version_number: "{{ item.version_number }}"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    unzip_dir: "/dev/shm/fastmlst-{{ version_number }}"
    install_dir: "{{ fastmlst_dir }}/{{ version_number }}"
  tags:
    - never
    - fastmlst{{ item.version_number }}
  block:
    - name: Download and install fastmlst ({{ version_number }})
      block:
        - name: Clone fastmlst repository
          git:
            repo: "{{ git_repo }}"
            dest: "{{ unzip_dir }}"
            version: "{{ git_tag }}"
            force: yes

        - name: Ensure fastmlst dir exists
          file:
            path: "{{ fastmlst_dir }}"
            state: directory
            recurse: yes

        - name: Copy fastmlst source to install directory
          command: "cp -r {{ unzip_dir }} {{ install_dir }}"
          args:
            creates: "{{ install_dir }}/setup.py"

        - name: Create uv virtual environment for fastmlst
          command: "/software/common/python/3.12.3/bin/uv venv {{ install_dir }}/venv --python /software/common/python/3.12.3/bin/python3"
          args:
            creates: "{{ install_dir }}/venv/bin/python"

        - name: Copy uv configuration files for fastmlst
          copy:
            src: "uv/bio/fastmlst/{{ version_number }}/{{ uv_file }}"
            dest: "{{ install_dir }}/{{ uv_file }}"
          loop:
            - "uv.lock"
            - "pyproject.toml"
          loop_control:
            loop_var: uv_file

        - name: Install fastmlst and dependencies with uv
          command: "/software/common/python/3.12.3/bin/uv sync"
          args:
            chdir: "{{ install_dir }}"
          environment:
            VIRTUAL_ENV: "{{ install_dir }}/venv"

    - name: Install fastmlst {{ version_number }} module
      block:
        - name: Check module dir {{ fastmlst_module_dir }}
          file:
            path: "{{ fastmlst_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install fastmlst {{ version_number }} module file
          template:
            src: bio/fastmlst.lua
            dest: "{{ fastmlst_module_dir }}/{{ version_number }}.lua"