---
- name: Install gubbins {{ item.version_number }}
  vars:
    gubbins_dir: "{{ bio_dir }}/gubbins"
    gubbins_module_dir: "{{ bio_modules }}/gubbins"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ gubbins_dir }}/{{ version_number }}"
  tags:
    - never
    - gubbins{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create gubbins directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.gubbins.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create gubbins module directory {{ gubbins_module_dir }}"
      file:
          path: "{{ gubbins_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install gubbins module file"
      template:
        src: bio/gubbins.lua
        dest: "{{ gubbins_module_dir }}/{{ version_number }}.lua"