---
- name: Install mlst {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    mlst_dir: "{{ bio_dir }}/mlst"
    mlst_module_dir: "{{ bio_modules }}/mlst"
    version_number: "{{ item.version_number }}"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    unzip_dir: "/dev/shm/mlst-{{ version_number }}"
    install_dir: "{{ mlst_dir }}/{{ version_number }}"
    blast_module: "{{ item.blast_module | default('blast/2.16.0') }}"
  tags:
    - never
    - mlst{{ item.version_number }}
  block:
    - name: Download and install mlst ({{ version_number }})
      block:
        - name: Clone mlst repository
          git:
            repo: "{{ git_repo }}"
            dest: "{{ unzip_dir }}"
            version: "{{ git_tag }}"
            force: yes

        - name: Ensure mlst dir exists
          file:
            path: "{{ mlst_dir }}"
            state: directory
            recurse: yes

        - name: Copy mlst to install directory
          command: "cp -r {{ unzip_dir }} {{ install_dir }}"
          args:
            creates: "{{ install_dir }}/bin"

        - name: Make mlst executables
          file:
            path: "{{ install_dir }}/bin/{{ mlst_script }}"
            mode: '0755'
          loop:
            - mlst
            - mlst-download_pub_mlst
            - mlst-make_blast_db
          loop_control:
            loop_var: mlst_script

        - name: Download MLST databases
          shell: "{{ install_dir }}/bin/mlst-download_pub_mlst"
          args:
            creates: "{{ install_dir }}/db"
          environment:
            PATH: "{{ install_dir }}/bin:{{ ansible_env.PATH }}"
          ignore_errors: yes

    - name: Install mlst {{ version_number }} module
      block:
        - name: Check module dir {{ mlst_module_dir }}
          file:
            path: "{{ mlst_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install mlst {{ version_number }} module file
          template:
            src: bio/mlst.lua
            dest: "{{ mlst_module_dir }}/{{ version_number }}.lua"