---
- name: Install panaroo {{ item.version_number }}
  vars:
    panaroo_dir: "{{ bio_dir }}/panaroo"
    panaroo_module_dir: "{{ bio_modules }}/panaroo"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ panaroo_dir }}/{{ version_number }}"
  tags:
    - never
    - panaroo{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create panaroo directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.panaroo.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create panaroo module directory {{ panaroo_module_dir }}"
      file:
          path: "{{ panaroo_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install panaroo module file"
      template:
        src: bio/panaroo.lua
        dest: "{{ panaroo_module_dir }}/{{ version_number }}.lua"