---
- name: Install prodigal {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    prodigal_dir: "{{ bio_dir }}/prodigal"
    prodigal_module_dir: "{{ bio_modules }}/prodigal"
    version_number: "{{ item.version_number }}"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    unzip_dir: "/dev/shm/prodigal-{{ version_number }}"
    install_dir: "{{ prodigal_dir }}/{{ version_number }}"
  tags:
    - never
    - prodigal{{ item.version_number }}
  block:
    - name: Download and install prodigal ({{ version_number }})
      block:
        - name: Clone prodigal repository
          git:
            repo: "{{ git_repo }}"
            dest: "{{ unzip_dir }}"
            version: "{{ git_tag }}"
            force: yes

        - name: Ensure prodigal dir exists
          file:
            path: "{{ prodigal_dir }}"
            state: directory
            recurse: yes

        - name: Create install directory
          file:
            path: "{{ install_dir }}/bin"
            state: directory
            recurse: yes

        - name: Compile prodigal
          make:
            chdir: "{{ unzip_dir }}"
            jobs: "{{ ansible_processor_count }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_count }}"

        - name: Install prodigal binary
          copy:
            src: "{{ unzip_dir }}/prodigal"
            dest: "{{ install_dir }}/bin/prodigal"
            mode: '0755'
            remote_src: yes

    - name: Install prodigal {{ version_number }} module
      block:
        - name: Check module dir {{ prodigal_module_dir }}
          file:
            path: "{{ prodigal_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install prodigal {{ version_number }} module file
          template:
            src: bio/prodigal.lua
            dest: "{{ prodigal_module_dir }}/{{ version_number }}.lua"