---
- name: Install pymlst {{ item.version_number }}
  vars:
    pymlst_dir: "{{ bio_dir }}/pymlst"
    pymlst_module_dir: "{{ bio_modules }}/pymlst"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ pymlst_dir }}/{{ version_number }}"
  tags:
    - never
    - pymlst{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create pymlst directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.pymlst.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create pymlst module directory {{ pymlst_module_dir }}"
      file:
          path: "{{ pymlst_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install pymlst module file"
      template:
        src: bio/pymlst.lua
        dest: "{{ pymlst_module_dir }}/{{ version_number }}.lua"