---
- name: Install rgi {{ item.version_number }}
  vars:
    rgi_dir: "{{ bio_dir }}/rgi"
    rgi_module_dir: "{{ bio_modules }}/rgi"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ rgi_dir }}/{{ version_number }}"
  tags:
    - never
    - rgi{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create rgi directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.rgi.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create rgi module directory {{ rgi_module_dir }}"
      file:
          path: "{{ rgi_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install rgi module file"
      template:
        src: bio/rgi.lua
        dest: "{{ rgi_module_dir }}/{{ version_number }}.lua"