---
- name: Install srst2 {{ item.version_number }}
  vars:
    srst2_dir: "{{ bio_dir }}/srst2"
    srst2_module_dir: "{{ bio_modules }}/srst2"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ srst2_dir }}/{{ version_number }}"
  tags:
    - never
    - srst2{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create srst2 directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.srst2.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create srst2 module directory {{ srst2_module_dir }}"
      file:
          path: "{{ srst2_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install srst2 module file"
      template:
        src: bio/srst2.lua
        dest: "{{ srst2_module_dir }}/{{ version_number }}.lua"