---
- name: Install srst2 {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    srst2_dir: "{{ bio_dir }}/srst2"
    srst2_module_dir: "{{ bio_modules }}/srst2"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ srst2_dir }}/{{ version_number }}"
  tags:
    - never
    - srst2{{ item.version_number }}
  block:
    - name: Download and install srst2 ({{ version_number }})
      block:
        - name: Ensure srst2 dir exists
          file:
            path: "{{ srst2_dir }}"
            state: directory
            recurse: yes

        - name: Create Python virtual environment for srst2
          command: "{{ python_location }}/bin/python3 -m venv {{ install_dir }}"
          args:
            creates: "{{ install_dir }}/bin/activate"

        - name: Upgrade pip in virtual environment
          pip:
            name: pip
            state: latest
            virtualenv: "{{ install_dir }}"

        - name: Install srst2 dependencies
          pip:
            name:
              - scipy
              - pysam
            virtualenv: "{{ install_dir }}"

        - name: Install srst2 using pip
          pip:
            name: srst2
            virtualenv: "{{ install_dir }}"

    - name: Install srst2 {{ version_number }} module
      block:
        - name: Check module dir {{ srst2_module_dir }}
          file:
            path: "{{ srst2_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install srst2 {{ version_number }} module file
          template:
            src: bio/srst2.lua
            dest: "{{ srst2_module_dir }}/{{ version_number }}.lua"