---
- name: Install virsorter2 {{ item.version_number }}
  vars:
    virsorter2_dir: "{{ bio_dir }}/virsorter2"
    virsorter2_module_dir: "{{ bio_modules }}/virsorter2"
    version_number: "{{ item.version_number }}"
    python_location: "{{ item.python_location | default('/software/common/python/3.11.2') }}"
    install_dir: "{{ virsorter2_dir }}/{{ version_number }}"
  tags:
    - never
    - virsorter2{{ item.version_number }}
  environment:
    PATH: "{{ python_location }}/bin:{{ ansible_env.PATH }}"
  block:
    - name: Create virsorter2 directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: true
    - name: Copy uv files
      copy:
        src: "bio/{{ uv_file }}.virsorter2.{{ version_number }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
        remote_src: false
        mode: ugo=r
      loop:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: "uv_file"
    - name: Create virtual environment
      command: "uv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: "Create virsorter2 module directory {{ virsorter2_module_dir }}"
      file:
          path: "{{ virsorter2_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install virsorter2 module file"
      template:
        src: bio/virsorter2.lua
        dest: "{{ virsorter2_module_dir }}/{{ version_number }}.lua"